### ISSUE TITLE
when i use this plugins, webpack-deep-scope-analysis-plugin did not reduce the size of the lodash-es library.

### ISSUE THREAD

**Issue by staticdeng** [vincentdchan/webpack-deep-scope-analysis-plugin#11]

**Comment by staticdeng** [comment]
Has anyone ever encountered this situation?

**Comment by LeoEatle** [comment]
Please provide your webpack configuration and babel configuration. If you use babel, please set `module: false` to avoid transforming es6 module to commonjs module.

**Comment by staticdeng** [comment]
sorry, i use lodash-es like this:
```
import lodash from 'lodash-es'
lodash.isArray([1, 2, 3])
```
when i use webpack-deep-scope-analysis-plugin, it did not reduce the size of the lodash-es
and then i in a different way use lodash-es
```
import { lodash } from 'lodash-es'
isArray([1, 2, 3])
```
then the build size reduced

**Comment by staticdeng** [comment]
but i find new question,  i use webpack v4.29.6, i find it don't need this webpack-deep-scope-analysis-plugin to reduce size, the webpack can reach tree-shaking by itself instead of use webpack-deep-scope-analysis-plugin. Has webpack integrated the functionality of webpack-deep-scope-analysis-plugin?

**Comment by LeoEatle** [comment]
> but i find new question, i use webpack v4.29.6, i find it don't need this webpack-deep-scope-analysis-plugin to reduce size, the webpack can reach tree-shaking by itself instead of use webpack-deep-scope-analysis-plugin. Has webpack integrated the functionality of webpack-deep-scope-analysis-plugin?

You misunderstand what the plugin do. 
If you use `import { isArray } from 'lodash-es'`, the other modules will not be imported. This is what we call static analysis. It's a ES6 specification and the optimization is provided by webpack. 
But `webpack-deep-scope-analysis-plugin` analysis scope for further optimization. You can read writer's [medium](https://medium.com/webpack/better-tree-shaking-with-deep-scope-analysis-a0b788c0ce77) for more detail.

**Comment by staticdeng** [comment]
If that's the case, webpack-deep-scope-analysis-plugin really doesn't reduce the size of the lodash-es library, so I'll provide a demo when I have time.

**Comment by staticdeng** [comment]
this is the demo that doesn't reduce the size of the lodash-es library:
https://github.com/stickypaper/tree-shaking
please help me find the reason, thanks you very much!

**Comment by vincentdchan** [comment]
@dzfrontend don't know if you have solved this. In your repo, do NOT use default import just like `import lodash from 'lodash-es';` because it can't be analyzed. Use namespace import:
`import * as lodash from 'lodash-es';`

**Comment by LeoEatle** [comment]
@dzfrontend Check this out.
![image](https://user-images.githubusercontent.com/14247110/55230404-b3e25680-525a-11e9-99be-3ea405adbbb8.png)


Before using `webpack-deep-scope-analysis-plugin`:

![image](https://user-images.githubusercontent.com/14247110/55230474-e68c4f00-525a-11e9-985a-63e8e55c0168.png)

After using  `webpack-deep-scope-analysis-plugin`:


![image](https://user-images.githubusercontent.com/14247110/55230484-edb35d00-525a-11e9-8eeb-81c1250974bf.png)

**Comment by LeoEatle** [comment]
@dzfrontend check my [article](https://leoeatle.github.io/techBlog/2018/08/27/%E9%87%8A%E6%94%BEwebpack%E7%9A%84%E7%9C%9F%E6%AD%A3%E6%BD%9C%E5%8A%9B/) for more info.
