### ISSUE TITLE
打包后出现语法错误

### ISSUE THREAD

**Issue by rock777777** [vincentdchan/webpack-deep-scope-analysis-plugin#14]
![image](https://user-images.githubusercontent.com/9247733/61352876-08105580-a8a1-11e9-9b09-444c673c7b80.png)
如上图
使用webpack-deep-scope-plugin插件打包后，本应该自运行函数，然而编译成了函数表达式，导致语法错误，tsconfig.json文件的target设置为es6

**Comment by vincentdchan** [comment]
麻烦开 development 模式，开启我列的这几个参数，看看输出有没有问题：
```
module.exports = {
  mode: 'development',
  plugins: [
    new WebpackDeepScopeAnalysisPlugin(),
  ],
  devtool: 'none',
  optimization: {
       usedExports: true,
       concatenateModules: true, occurrenceOrder: true // To keep filename consistent between different modes (for example building only)
   },
};

```

**Comment by rock777777** [comment]
按照你说的参数都试过了，还是没有解决问题，依然是函数表达式语法错误，问题与这个issue一致，他里面有个demo，您可以测试一下，感谢！[#15](https://github.com/vincentdchan/webpack-deep-scope-analysis-plugin/issues/15)

**Comment by vincentdchan** [comment]
参数是用来 debug  的，加了参数之后输出结果看看哪里出了问题

**Comment by vincentdchan** [comment]
更新到最新版本
