### ISSUE TITLE
bundle package raise error Uncaught TypeError: (void 0) is not a function

### ISSUE THREAD

**Issue by jiawang1** [vincentdchan/webpack-deep-scope-analysis-plugin#15]
hi:
I try to use this plugin to reduce final bundle size, but some modules not shaking correctly. I have installed react-beautiful-dnd base on create-react-app. And only import the module in index.js and change one line of code: 

import { Draggable, Droppable, DragDropContext } from "react-beautiful-dnd";
ReactDOM.render(<DragDropContext onDragEnd={()=>{}}><App /></DragDropContext>, document.getElementById('root'));

the final bundle raise error 
Uncaught TypeError: (void 0) is not a function.

could you please have a look. I have create a repo : https://github.com/jiawang1/test-webpack-plugin

Jay

**Comment by vincentdchan** [comment]
Same problem with #10 , please upgrade to the latest version.
