### ISSUE TITLE
Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by hmz5** [vincentdchan/webpack-deep-scope-analysis-plugin#17]
webpack-deep-scope-plugin 1.6.2
webpack 4.40.2

module-a.js
```javascript
import lodash from 'lodash-es'

export * from './module-b'

export const func1 = function(value) {
  return lodash.isArray(value)
}

export const func2 = function() {
  console.log('这是func2')
  return 123123
}
```

```javascript
export const func3 = () => {
  console.log('B模块的func3方法')
}
```

index.js
```javascript
import { func2 } from './module-a'

func2()
```

webpack.config.js
```javascript
const path = require('path')
const WebpackDeepScopeAnalysisPlugin = require('webpack-deep-scope-plugin')
  .default
const HtmlWebpackPlugin = require('html-webpack-plugin')
module.exports = {
  //   mode: 'development',
  mode: 'production',
  entry: './index.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'index.bundle.js',
  },
  plugins: [
    new WebpackDeepScopeAnalysisPlugin(),
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: 'index.html',
    }),
  ],
}
```

![image](https://user-images.githubusercontent.com/16495308/65019564-0bd25e00-d95e-11e9-9ae8-2dddcfcdc931.png)

**Comment by vincentdchan** [comment]
Please go to node_modules/deep-scope-analyser/package.json and tell me the version of this package. Thanks.

**Comment by hmz5** [comment]
> Please go to node_modules/deep-scope-analyser/package.json and tell me the version of this package. Thanks.

"version": "1.7.0"

**Comment by hmz5** [comment]
> Please go to node_modules/deep-scope-analyser/package.json and tell me the version of this package. Thanks.
有解码？

**Comment by hmz5** [comment]
> Please go to node_modules/deep-scope-analyser/package.json and tell me the version of this package. Thanks.

有解吗？

**Comment by vincentdchan** [comment]
回到 #10 讨论
