### ISSUE TITLE
What's the latest version?

### ISSUE THREAD

**Issue by gustavoschmidt** [vincentdchan/webpack-deep-scope-analysis-plugin#21]
On Github the latest release is version 1.6.1 but on Yarn is 1.6.2. Am I missing anything?
Thanks!

Github:
https://github.com/vincentdchan/webpack-deep-scope-analysis-plugin/releases

Yarn: 
https://yarnpkg.com/package/webpack-deep-scope-plugin

**Comment by vincentdchan** [comment]
1.6.1 published on npm doesn't compile correctly. 1.6.2 on npm matches 1.6.1 on Github.

**Comment by gustavoschmidt** [comment]
Thanks!
