### ISSUE TITLE
Cannot read property 'generateExportInfo' of undefined

### ISSUE THREAD

**Issue by LeoEatle** [vincentdchan/webpack-deep-scope-analysis-plugin#5]
Hey, I tried your plugin in a simple demo and it works well. Now I want to apply it to my team project which is much bigger. Then it failed and throw this error.

![image](https://user-images.githubusercontent.com/14247110/44641657-97e3b180-a9fa-11e8-8cff-1395d27d4e6b.png)

Here is the environment:
Node v8.11.3
webpack v4.17.1

Here are part of used plugins:
```
new webpack.optimize.ModuleConcatenationPlugin(),
new webpack.HashedModuleIdsPlugin(),
new WebpackDeepScopeAnalysisPlugin()
```

I can't figure out if it is my mistake or a bug of this plugin.

**Comment by vincentdchan** [comment]
It seems that other plugin change the module that my plugin can not find some of them. I am going to debug with `ModuleConcatenationPlugin`.

**Comment by LeoEatle** [comment]
Yes. If I remove `webpack.optimize.ModuleConcatenationPlugin`, it works well.
My project is a `multi-entry` project. So I don't think `ModuleConcatenationPlugin` is helpful here. 
Is multiple entry the reason why it failed?

**Comment by vincentdchan** [comment]
Hi, @LeoEatle . I have published a pre-release version for this case. I want you to try it and I suppose it doesn't crash now.

Please upgrade to `webpack-deep-scope-plugin@1.5.3-0`.

**Comment by vincentdchan** [comment]
@LeoEatle Multi-entry can't make it crash. It crashed because `ModuleConcatenationPlugin` concats  modules and my plugin can't find the analysis result of concatenation modules.

**Comment by LeoEatle** [comment]
OK, I tried `webpack-deep-scope-plugin@1.5.3-0` and there's no error anymore. I think I can close this issue now. 
Though, I don't find out any difference in size of the final bundle js files. I need to find out whether my code are free of these scope issues or the plugin is not working.

**Comment by vincentdchan** [comment]
@LeoEatle Check if your babel/ts transpiled your code into UMD/CommonJS(ES6 module is required for optimization). And please use library that uses ES6 module(lodash-es instead of lodash)
